# Generated by Django 5.2.4 on 2025-07-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[(1, 'user'), (2, 'supervisor')], default=(1, 'user')),
        ),
    ]
