# Generated by Django 5.2.4 on 2025-07-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_users_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizzes',
            name='types',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.AddField(
            model_name='quizzes',
            name='types',
            field=models.JSONField(choices=[(1, 'multiple choice'), (2, 'boolean'), (3, 'dropdown'), (4, 'numerical')], default=(1, 'multiple choice')),
        ),
    ]
