# Generated by Django 5.2.4 on 2025-07-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_quizzes_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzes',
            name='types',
            field=models.JSONField(choices=[(1, 'multiple choice'), (2, 'boolean'), (3, 'dropdown'), (4, 'numerical')], default=list),
        ),
    ]
