# Generated by Django 5.2.4 on 2025-07-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_quizzes_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzes',
            name='types',
            field=models.JSONField(),
        ),
    ]
