# Generated by Django 5.2.4 on 2025-07-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_quizzes_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='uuid_id',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='uuid_id',
        ),
        migrations.AddField(
            model_name='questions',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='quizzes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
